### PR TITLE
Feature/412 profile overhaul

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #412 
Enforce password
[Kazam_screencast_00084.webm](https://github.com/kartoza/miniSASS/assets/7352963/ab504671-87ec-4052-a207-8bb3c471399e)

Upload certificate
[Kazam_screencast_00085.webm](https://github.com/kartoza/miniSASS/assets/7352963/73d53fcf-1544-45d5-aa45-b91135e75c07)

Update profile
[Kazam_screencast_00088.webm](https://github.com/kartoza/miniSASS/assets/7352963/6fe01dcc-5952-4e73-9b04-750c761464b6)

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 19 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 33 sec

**Comment by NyakudyaA** [comment]
Is this ready for review or you are going to cover other aspects like email notifications in a follow-up PR

**Comment by tinashechiraya** [comment]
@zamuzakki can you resolve the conflicts

**Review by tinashechiraya — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 25 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 31 sec

**Pull request merged**
