### PR TITLE
Landing page manual

### PR DESCRIPTION
**Pull request by ketankartoza**
This  PR is for issue #430 

@amyburness I have taken 1 hour extra because the site has not been working for some time, find what the issue is with the `Admin` button on the site.

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 30 sec

**Review by amyburness — APPROVED** [review]
This looks good, Simple with the right amount of detail. I have made a few edits to the typology.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 36 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 23 sec

**Pull request merged**
