### PR TITLE
feat: prevent proceeding to next form if mandatory fields are empty

### PR DESCRIPTION
**Pull request by tinashechiraya**
The form will highlight the mandatory fields and if they're not filled shows a message and disables the next button 

for issue:
https://github.com/kartoza/miniSASS/issues/617

https://github.com/kartoza/miniSASS/assets/70011086/20a746b1-eef7-438d-a6ca-43c9cd73bfeb

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 34 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 28 sec

**Review by zamuzakki — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 11 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 35 sec

**Pull request merged**
