### PR TITLE
Observation information panel for sites

### PR DESCRIPTION
**Pull request by tinashechiraya**
Description:
this addresses ticket issue #369 ,the frontend part only ...the backend will be in a different pr

now when the user clicks on any map area 
the coordinates of that location will be captured 
and a query will be made ,
the query will be to search if there is any site in the db with matching coordinates
if found , the site and its observations data will be returned 
and these willl be rendered on the observation details form .
the tabs are now fully dynamic ,as well as the images 

https://github.com/kartoza/miniSASS/assets/70011086/798fc984-7c8c-48a7-b744-69545aa3fa28

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 1 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 55 sec

**Review by NyakudyaA — COMMENTED** [review]
Isn't it expensive to send a query for every point clicked. I thought we wanted to get feature info for the crabs only not for every map point. Mvt should already have a way to retrieve the info from a point eg https://openlayers.org/en/latest/examples/vector-tile-info.html
The idea was click on a crab and observation panel opens, click on any part of map then nothing happens 

@NyakudyaA can you provide a little more context so I know how to implement what you're suggesting. The idea is that when a user clicks a location on the map , if there is a site on that location , it should show that sites details (these include the observations and images etc) so through the method you suggested how is that achieved? ,where will the information be coming from if not from our db?

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 21 sec

**Comment by NyakudyaA** [comment]
> Isn't it expensive to send a query for every point clicked. I thought we wanted to get feature info for the crabs only not for every map point. Mvt should already have a way to retrieve the info from a point eg https://openlayers.org/en/latest/examples/vector-tile-info.html
> The idea was click on a crab and observation panel opens, click on any part of map then nothing happens 
> 
> @NyakudyaA can you provide a little more context so I know how to implement what you're suggesting. The idea is that when a user clicks a location on the map , if there is a site on that location , it should show that sites details (these include the observations and images etc) so through the method you suggested how is that achieved? ,where will the information be coming from if not from our db?
> 
> 

With your method can you only restrict  clicking a crab and retrieving the information. What I was just worried was that for each point clicked it sends a query to the api end point.

Alternatively what I am suggesting is to use the service
https://minisass.dev.do.kartoza.com/tiles/ just click on preview you will see that each point can be clicked and information about that point will be visible. Since you have already an API you can get the site_id and pass it to your API or totally populate the side panel with the dictionary you get from the service. 

The example I gave you there was for open layers but I am sure there is an example of how to do the same in react 



Clicking on any other part of the map doesn't result in any information being shown or a query being sent to the backend

**Comment by tinashechiraya** [comment]
@NyakudyaA Alright I see , It seems more efficient , let me do it that way. 
Also how will we get the observations saved in the db to reflect on the map when they're saved via the data input form?

**Comment by NyakudyaA** [comment]
The observation will be dynamic, anything in the DB will be served directly and immediately visible. I am going to update the service to link to the observation layer after I have migrated the data

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 3 min 57 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 4 min 32 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 9 sec

**Comment by tinashechiraya** [comment]
@NyakudyaA can we merge this for now and make the improvements in todo , they're other things needed in this pr on the site

**Review by NyakudyaA — APPROVED** [review]
Can you add tickets for the TODO @tinashechiraya

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 30 sec

**Pull request merged**
