### PR TITLE
feature/511: Update geopackage download

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #511 
Folder structures:
[Kazam_screencast_00095.webm](https://github.com/kartoza/miniSASS/assets/7352963/9e392c27-e398-4977-9101-60d5adcbbb48)

Downloaded files:
image

**Note**
When we download geopackage, pest, pest image, and site image tables are downloaded as CSV since they don't have geometry field.

Example of downloaded files
[observations.zip](https://github.com/kartoza/miniSASS/files/13836337/observations.zip)

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 5 min 59 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 6 min 0 sec

**Review by NyakudyaA — COMMENTED** [review]
Looks good @zamuzakki 
Can we add the following tables
* observation_images.csv
* pests.csv
* site_images.csv

to the geopackage. As for the relationships we need to either link them up or give a small readme that explains the relationship between the tables

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 6 min 26 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 5 min 50 sec

**Comment by zamuzakki** [comment]
@NyakudyaA I've updated the geipackage
[observations(4).zip](https://github.com/kartoza/miniSASS/files/13860825/observations.4.zip)

**Review by NyakudyaA — CHANGES_REQUESTED** [review]
The observations layer in the geopackage doesn't have a CRS assigned to it. We need to assign 4326 when you creating the geopackage.

As a follow up I will share the style file to use with the layers in QGIS or even a QGIS project but we can merge if the CRS is sorted

**Comment by zamuzakki** [comment]
@NyakudyaA I've set the CRS
[observations.zip](https://github.com/kartoza/miniSASS/files/13882613/observations.zip)

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 4 sec

**Review by NyakudyaA — APPROVED** [review]
Can you also add the following QGIS project 
[observations.zip](https://github.com/kartoza/miniSASS/files/13884847/observations.zip)

Into the exports folder. This will allow users to open the project with defined relations. You need to unzip it

**Comment by zamuzakki** [comment]
@NyakudyaA I have added the QGIS project
[observations.zip](https://github.com/kartoza/miniSASS/files/13887607/observations.zip)

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 34 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 44 sec

**Pull request merged**
