### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by tinashechiraya**
https://github.com/kartoza/miniSASS/assets/70011086/1a0684df-de0b-4e8b-824d-fde7a89a11ac

email

https://github.com/kartoza/miniSASS/assets/70011086/17c058a9-9c85-4c35-be2a-8e644a205976

Description:
I have added salutations and logo to the contact us email template
I have added some validations before the contact us form is submitted
I have added an additional column to be shown on the group scores in the admin
The group scores are now being calculated as you add them

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 0 sec

**Comment by tinashechiraya** [comment]
@NyakudyaA you can approve .its all good

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 5 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 6 sec

**Review by NyakudyaA — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 18 sec

**Pull request merged**
