### PR TITLE
Docs: Docs site updates.

### PR DESCRIPTION
**Pull request by Jeremy-Prior**
-  Made docs site build correctly with working indexes
- Fixed minor build warnings

### CODE REVIEW

**Comment by Jeremy-Prior** [comment]
Converting to a draft until other docs updates have been added and I can test them locally

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 25 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 16 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 33 sec

**Review by amyburness — APPROVED** [review]
Thanks @Jeremy-Prior this looks great.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 30 sec

**Pull request merged**
