### PR TITLE
Fix/837: crab click

### PR DESCRIPTION
**Pull request by zamuzakki**
This PR is for #837 
Demo:
https://youtu.be/-IiEPpCCnuk

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 12 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 11 min

**Review by tinashechiraya — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 11 min

**Review by NyakudyaA — COMMENTED** [review]
@zamuzakki This solution is prone to some flaws in the end. If the json gets changed what happens to your implementation in terms of pixel sizes and the conversions you have done ?
GFI should not be affected by the styling done on the service. We can leave this as it is for now but maybe add a **TODO** in the implementation to do it in a standard way

**Pull request merged**
