### PR TITLE
Feature/302 download observation

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR #302 
[Kazam_screencast_00070.webm](https://github.com/kartoza/miniSASS/assets/7352963/5e2fff1a-e862-4c11-b332-0b3c3b0435aa)

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 1 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 26 sec

**Review by NyakudyaA — COMMENTED** [review]
@zamuzakki Does the date picker restrict the date range if it's a single observation ?

**Comment by zamuzakki** [comment]
@NyakudyaA It doesn't. But I can add it if it's a single observation.

**Review by tinashechiraya — APPROVED** [review]
LGTM

**Comment by NyakudyaA** [comment]
> @NyakudyaA It doesn't. But I can add it if it's a single observation.

We should add it otherwise a user might get confused about why he is choosing a date range for just a single observation.

Also is the download inclusive of the start and end date selected ?

**Comment by zamuzakki** [comment]
@NyakudyaA I'm currently adding it. Yes, the download is inclusive of the start and end date selected ?.

**Comment by zamuzakki** [comment]
@NyakudyaA I'm closing this PR and combined it to https://github.com/kartoza/miniSASS/pull/372

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 4 sec

**Pull request closed without merging**
