### PR TITLE
explicitly define PK

### PR DESCRIPTION
**Pull request by NyakudyaA**
When creating a new user account you encounter the following
image (2)

This explicitly defines the PK

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 3 sec

**Comment by tinashechiraya** [comment]
LGTM

**Comment by tinashechiraya** [comment]
@NyakudyaA we can set the AUTO_FIELD in the settings.py . I'll update the settings later

**Review by tinashechiraya — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 4 sec

**Pull request merged**
