### PR TITLE
Authenticate with email

### PR DESCRIPTION
**Pull request by tinashechiraya**
https://github.com/kartoza/miniSASS/assets/70011086/394df6ab-30c3-44fa-857b-6f0f7dbdddb8

The username field has also been removed from the registration

https://github.com/kartoza/miniSASS/assets/70011086/2f1db575-c62a-41ef-81cf-03eb5299ae56

added a loader on login

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 5 min 11 sec

**Review by NyakudyaA — COMMENTED** [review]
Are we sure that all users (past) have valid email addresses and users still remember them? . If we are going this route I think we need to handle the following:

* allow previous users to login with username and on first login update their email address
* Add a message on the login page like "If you do not remember your email , please send a message to the admins using the contact us form. Please include your previous username and your preferred email address and an admins will update it for you.
 Either option should work 

@NyakudyaA I have an idea, we can have everybody login with the username only once then notify them that from now on the system uses emails for login and then it will show them their current email address saved on the system.

@NyakudyaA we had a chat with @Amy earlier we have agreed to show the message that users should now switch to email , this image will be displayed for a few days then removed. Is this fine

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 16 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 55 sec

**Review by zamuzakki — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 48 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 40 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 49 sec

**Comment by NyakudyaA** [comment]
> Are we sure that all users (past) have valid email addresses and users still remember them? . If we are going this route I think we need to handle the following:
> 
>     * allow previous users to login with username and on first login update their email address
> 
>     * Add a message on the login page like "If you do not remember your email , please send a message to the admins using the contact us form. Please include your previous username and your preferred email address and an admins will update it for you.
>       Either option should work
> 
> 
> @NyakudyaA I have an idea, we can have everybody login with the username only once then notify them that from now on the system uses emails for login and then it will show them their current email address saved on the system.
> 
> @NyakudyaA we had a chat with @amy earlier we have agreed to show the message that users should now switch to email , this image will be displayed for a few days then removed. Is this fine

@tinashechiraya The functionality will be removed after 7 days is a bit too vague for me. Is it 7 days from the day the site is launched or 7 days from when a user access the site. We can't assume that the site will be accessed within a week by all past users

**Pull request merged**
