### PR TITLE
Feature/728 prevent select ocean

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #728 

https://github.com/kartoza/miniSASS/assets/7352963/fbb9c6a3-2ca8-4141-af74-963da60903af

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 35 sec

**Review by tinashechiraya — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 16 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 30 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 36 sec

**Pull request merged**
