### PR TITLE
Images placeholder on observations

### PR DESCRIPTION
**Pull request by tinashechiraya**
when the the observation opened or site has no images available instead of showing a blank space an image placeholder will appear

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 47 sec

**Review by NyakudyaA — APPROVED** [review]
Could we either have a different placeholder for the site and observations? ie
Site 
image

Observation
Some image with pests i.e
image
Also will all the historical sites show the placeholder images?

**Comment by tinashechiraya** [comment]
@NyakudyaA okay I wil use these as placeholder and yes all the historical sites will have this placeholder since they have no images

in ticket  https://github.com/kartoza/miniSASS/issues/580

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 29 sec

**Pull request merged**
