### PR TITLE
Update ux when selecting location site

### PR DESCRIPTION
**Pull request by dimasciput**
Updated : 

https://github.com/kartoza/miniSASS/assets/1979569/fd4ff23e-0078-4fc2-a3a4-14ebc44e7c58

Before : 

https://github.com/kartoza/miniSASS/assets/1979569/26c4e146-f27c-458e-a7e7-6b2838ffac0f

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 3 sec

**Comment by meomancer** [comment]
LGTM 
cc @dimasciput

**Review by meomancer — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 10 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 59 sec

**Pull request merged**
