### PR TITLE
patch: show minisass logo in registration email

### PR DESCRIPTION
**Pull request by tinashechiraya**

### CODE REVIEW

**Review by amyburness — APPROVED** [review]
make email more user friendly

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 13 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 33 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 3 min 17 sec

**Pull request merged**
