### PR TITLE
Reset map  when close datainput form

### PR DESCRIPTION
**Pull request by tinashechiraya**
https://github.com/kartoza/miniSASS/assets/70011086/48710dd8-700e-46cc-8c07-f8ead99883ca

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 4 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 16 sec

**Review by NyakudyaA — CHANGES_REQUESTED** [review]
I think we should not reset the map back. We already have a zoom to home as map icons. What happens if I want to add multiple observation at or near the same location. I think the correct behaviour is to just leave the map at it's current location and if a user needs to zoom back we have the button for that. 

@NyakudyaA resetting the map is not just for zooming out , there are cases when some map functions are activated like the cursor style having been changed when the user chose select on map or select site on map so when the user closes the form they should be deactivated as the user is no longer using them .

then for adding multiple observations on the same point etc the user can still achieve that as long as the sidebar panel (the data input form) is open they can continue to add observations as they like. closing it should be a sign they are done with adding observations thus returning the map functions to default . Is this not the correct behaviour ?

**Comment by NyakudyaA** [comment]
> I think we should not reset the map back. We already have a zoom to home as map icons. What happens if I want to add multiple observation at or near the same location. I think the correct behaviour is to just leave the map at it's current location and if a user needs to zoom back we have the button for that. 
> 
> @NyakudyaA resetting the map is not just for zooming out , there are cases when some map functions are activated like the cursor style having been changed when the user chose select on map or select site on map so when the user closes the form they should be deactivated as the user is no longer using them .
> 
> then for adding multiple observations on the same point etc the user can still achieve that as long as the sidebar panel (the data input form) is open they can continue to add observations as they like. closing it should be a sign they are done with adding observations thus returning the map functions to default . Is this not the correct behaviour ?

@tinashechiraya I understand that closing the form should deactivate the actions, but let's keep the zoom level at that level, remember that once a point is added it should be visible and a user would maybe want to click on the feature to look at the side details and hence zooming out would not be a good option as that point would becomd lost in the sea of other observations and if I am accessing this from Europe and after closing the form I get a view of South Africa is not the best option 

@NyakudyaA I see what you mean ,I will make the adjustment here

**Comment by tinashechiraya** [comment]
some of the issues here were resolved in merged prs

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 40 sec

**Pull request closed without merging**
