### PR TITLE
Maplibre integrations

### PR DESCRIPTION
**Pull request by meomancer**
Done:
- [x] Maplibre intergrations
- [x] Basemap layers
- [x] Overlay layers
- [x] Search by sites and nominatim

### CODE REVIEW

**Comment by meomancer** [comment]
Selection_032

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 2 min 57 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 53 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 18 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 36 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 2 sec

**Pull request merged**
