### PR TITLE
Navigate to observation on map

### PR DESCRIPTION
**Pull request by tinashechiraya**
Description:

when view details of an observation is clicked ,it navigates to the map page and zooms to the location of the observation

https://github.com/kartoza/miniSASS/assets/70011086/bdef2a4c-cb3e-4524-b2e9-ca567f1ebaac

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 3 min 25 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 38 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 38 sec

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 14 sec

**Pull request merged**
