### PR TITLE
Feature/501 observation images identifiable

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #501 
[Kazam_screencast_00096.webm](https://github.com/kartoza/miniSASS/assets/7352963/50c2d67f-f903-4544-9f22-d12106409247)

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 5 min 56 sec

**Comment by tinashechiraya** [comment]
@zamuzakki can you resolve the conflicts then I will merge it for you

**Review by tinashechiraya — APPROVED** [review]

**Comment by zamuzakki** [comment]
@tinashechiraya I have fixed the conflict.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 5 min 17 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 6 min 25 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 27 sec

**Pull request merged**
