### PR TITLE
featyre/612: UI update

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #612
Main Page
Screen Shot 2024-01-10 at 11 45 23-fullpage

 How To
Screen Shot 2024-01-10 at 11 44 01-fullpage

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 40 sec

**Comment by tinashechiraya** [comment]
@zamuzakki 
align

before they were aligned can you adjust the how to title so that it aligns

**Comment by zamuzakki** [comment]
@tinashechiraya Updated.
Do we want to make it overflow on mobile device, or make it fit to screen?
Screenshot from 2024-01-11 06-22-16
[Kazam_screencast_00112.webm](https://github.com/kartoza/miniSASS/assets/7352963/4c51f13a-a299-4260-9c91-eaec7046332e)

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 37 sec

**Review by tinashechiraya — APPROVED** [review]
LGTM

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 30 sec

**Pull request merged**
