### PR TITLE
Add resource link

### PR DESCRIPTION
**Pull request by zamuzakki**
[Kazam_screencast_00113.webm](https://github.com/kartoza/miniSASS/assets/7352963/5c07ae98-bafe-4b4e-9e3e-38801c6eca81)

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 43 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 38 sec

**Review by tinashechiraya — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 31 sec

**Comment by LunaAsefaw** [comment]
@zamuzakki the issue isn't that the resource link did not work, it is that it is different from the other links where you click anywhere int he green box and it navigates but for resources, it only worked when you click on the word.

**Comment by zamuzakki** [comment]
@LunaAsefaw I've made PR for that

**Pull request merged**
