### PR TITLE
Improve how to page

### PR DESCRIPTION
**Pull request by tinashechiraya**
howto

howto1

howto2

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 26 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 14 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 5 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 5 sec

**Review by NyakudyaA — APPROVED** [review]
Do we need to underline the hyperlinks like `Register`? etc

**Comment by tinashechiraya** [comment]
> Do we need to underline the hyperlinks like `Register`? etc

from the figma design that's how it is . I'm not sure what's best ,maybe we can remove it ?

**Comment by NyakudyaA** [comment]
If it's like that from the design then cool

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 0 sec

**Comment by dimasciput** [comment]
Screenshot 2023-11-08 at 2 40 53 PM

@tinashechiraya

**Comment by dimasciput** [comment]
@tinashechiraya icons missing
Screenshot 2023-11-08 at 2 43 49 PM

**Comment by dimasciput** [comment]
Screenshot 2023-11-08 at 2 44 26 PM

icons are different

**Comment by tinashechiraya** [comment]
> Screenshot 2023-11-08 at 2 44 26 PM
> 
> icons are different

@amyburness if you have the crab icons with different colors?

**Pull request merged**
