### PR TITLE
patch: update registration ui

### PR DESCRIPTION
**Pull request by tinashechiraya**
1. with this the horizontal scroll that appears on the registration has been completed modal has been removed 
2. the close icons position has been adjusted a little to the right
3. and the loading bar that was not showing now shows

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 29 sec

**Review by NyakudyaA — COMMENTED** [review]
Can you please add a GIF or image


https://github.com/kartoza/miniSASS/assets/70011086/8f429cd2-efb4-4c0c-9dba-50e08f57361b

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 6 min 38 sec

**Comment by tinashechiraya** [comment]
https://github.com/kartoza/miniSASS/assets/70011086/c8afae43-be48-470d-b3eb-54a495104e8b

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 5 min 25 sec

**Review by NyakudyaA — COMMENTED** [review]
What is the purpose of the username if we will be using email to log in. Should we not also have a character limit for the username, something simple like >4 chars

@NyakudyaA this pr is before the one that gets rid of the username so it's basically an update to existing functionality. And limiting the username to a number of characters might make it difficult for the users to create unique usernames as currently when registering ,the username has to be unique else registration will fail

**Comment by NyakudyaA** [comment]
> What is the purpose of the username if we will be using email to log in. Should we not also have a character limit for the username, something simple like >4 chars
> 
> @NyakudyaA this pr is before the one that gets rid of the username so it's basically an update to existing functionality. And limiting the username to a number of characters might make it difficult for the users to create unique usernames as currently when registering ,the username has to be unique else registration will fail

If the follow up PR removes the username then we can merge. In your screenshot your username was `c` and it allowed you to register. I think in the previous implementation there was a character limit and it doesn't affect users choosing unique values 

@NyakudyaA Oh for this its not really connected to the backend. I just made it bypass everything so that it can show the the loading bar as the purpose of this pr is just to add the loading bar and fix the registration form on the mobile view so the previous implementation you're referring to or the current way its working on staging is going to remain the same

**Review by NyakudyaA — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 57 sec

**Pull request merged**
