### PR TITLE
patch: navigate to map location on dms input

### PR DESCRIPTION
**Pull request by tinashechiraya**
https://github.com/kartoza/miniSASS/assets/70011086/6f51318e-b815-44a9-9442-c3ccaa03e9f0

Description
whilst entering dms values to the map will adjust to that location on the map

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 35 sec

**Review by NyakudyaA — COMMENTED** [review]
@tinashechiraya looks good but it looks to me like the zooming starts immediately as soon as a user starts writing something, can we implement a delay something like https://stackoverflow.com/questions/53071774/reactjs-delay-onchange-while-typing

**Comment by dimasciput** [comment]
I'm going to merge this for now due to time constraints.

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 49 sec

**Pull request merged**
