### PR TITLE
Add select site and forms updates

### PR DESCRIPTION
**Pull request by tinashechiraya**
https://github.com/kartoza/miniSASS/assets/70011086/8fffeaee-8f73-4958-bb9f-3768edd74d00

Description:
I have removed the extra white space on the sidebar panel
I have added the select site field when the select site button is clicked 
I have added the upload image on the manage images modal

this is only frontend implementation of the logic and flow ...the backend is still to be implemented

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 38 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 10 sec

**Review by NyakudyaA — COMMENTED** [review]
Can you add a gif that shows how `Type coordinates work`, I am worried that users might swap X and Y axis and have points rendering in the ocean or somewhere. What validation do we have to cater for that and when does the point being captured by the user show on the map. I think it might make sense to zoom to the site that has just been populated so that a user can see where they are especially for `Typed coordinates`

Also, I feel all panels should be on the other side below the blue navbar. @amyburness your thoughts

**Comment by tinashechiraya** [comment]
this has been merged via pr #226

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 39 sec

**Pull request closed without merging**
