### PR TITLE
Add zoom to selected sites

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #712 and #707
Also prevent deletion of validated image file
[Kazam_screencast_00123.webm](https://github.com/kartoza/miniSASS/assets/7352963/bab2d2ac-47c8-4809-a7f8-6026acc977d2)

### CODE REVIEW

**Review by NyakudyaA — APPROVED** [review]
@zamuzakki Won't we have a glitch if I randomly select sites very fast, like I choose A, then B etc and the map zooms to these all the time ?, Is there a time delay to ensure the user has chosen this site?

**Comment by zamuzakki** [comment]
@NyakudyaA We can add delay for that. I'll find out the appropriate value.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 39 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 51 sec

**Comment by zamuzakki** [comment]
@NyakudyaA This is the updated 
[Kazam_screencast_00125.webm](https://github.com/kartoza/miniSASS/assets/7352963/b0401fdf-cab2-4204-95cf-7cd8a7428c2a)
delay:

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 49 sec

**Pull request merged**
