### PR TITLE
Create manual structure

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for issue #425

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 45 sec

**Comment by ketankartoza** [comment]
@amyburness please review this PR because this PR is for the base structure of the manual.

**Review by NyakudyaA — APPROVED** [review]
@ketankartoza please tag @Jeremy-Prior for documentation reviews

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 23 sec

**Comment by ketankartoza** [comment]
> @ketankartoza please tag @Jeremy-Prior for documentation reviews

@NyakudyaA I discussed with @amyburness to tag her in the documentation PRs because @Jeremy-Prior is on leave till 2nd Jan.

**Comment by ketankartoza** [comment]
> @ketankartoza please tag @Jeremy-Prior for documentation reviews

@NyakudyaA I discussed with @amyburness to tag her in the documentation PRs because @Jeremy-Prior is on leave till 2nd Jan.

**Pull request merged**
