### PR TITLE
Fix Django runtime

### PR DESCRIPTION
**Pull request by zamuzakki**
This PR removes duplicate imports and fixes Django Runtime due to missing comma.

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 40 sec

**Review by NyakudyaA — APPROVED** [review]

**Comment by NyakudyaA** [comment]
Can you fix conflicts @zamuzakki

**Comment by zamuzakki** [comment]
I'm on it  @NyakudyaA

**Comment by zamuzakki** [comment]
@NyakudyaA conflict resolved.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 43 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 25 sec

**Pull request merged**
