### PR TITLE
Add assessment model and relationships

### PR DESCRIPTION
**Pull request by tinashechiraya**
Description
this pr replaces update site models https://github.com/kartoza/miniSASS/pull/364
defines assessment model and a relationship to the site 
also added a few more fields for the observation model , these will be used for machine learning

assessments_table

assessment_api_view

crud_on_assessment

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 57 sec

**Review by dimasciput — APPROVED** [review]

**Comment by dimasciput** [comment]
@tinashechiraya please fix the conflicts

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 30 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 56 sec

**Pull request merged**
