### PR TITLE
Token authentication 3rd party api

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for the issue #1097

### CODE REVIEW

**Comment by EliVolsch** [comment]
@ketankartoza Just want to check in and make sure you're aware this section needs to be changed as the URL is no longer the correct way to have a token generated

image

**Comment by ketankartoza** [comment]
@EliVolsch, I am going to change the documentation for the token. I will open a PR for it today thanks!!

**Review by amyburness — APPROVED** [review]
LGTM 
@tinashechiraya @EliVolsch let me know if you have any comments otherwise I will merge this asap

**Comment by tinashechiraya** [comment]
@amyburness looks good to me

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 53 sec

**Pull request merged**
