### PR TITLE
Frontend UI fixes

### PR DESCRIPTION
**Pull request by tinashechiraya**
https://github.com/kartoza/miniSASS/assets/70011086/09fb855f-124a-4953-8593-b1f2648871b1

I have added a gap between the footer text and the social icons
I have made the text for how to, contact us, not to wrap and appear on one line
I have added a replacement logo for the footer until one with better quality is provided 
I have added the reset password page ,where the user can request for a password reset and can also update their password
the page is dynamic it will be responsible for updating the user password and also sending the email and also changing the password when logged in as it renders different components based on user intentions
I have aligned the items on the home page to all start on the same position 
I have added some spacing on the introduction text so the design matches the figma design
I have added the learn more text to the article buttons
I have made the buttons on how to and home page the same length
I have also added geo location that uses navigator.geolocation , the user will be asked to grant permission to the browser to read his or her location ,once access is granted the country dropdown will be automatically filled with the users country.

https://github.com/kartoza/miniSASS/assets/70011086/76ba4ff7-89a8-46e0-a281-8c58dfcfff17

I added svgs for color crabs

color_crabs

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 59 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 18 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 4 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 33 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 9 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 47 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 57 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 56 sec

**Comment by NyakudyaA** [comment]
@LunaAsefaw Can you check this out since you started looking at the UI?

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 16 sec

**Pull request merged**
