### PR TITLE
Feature/332 326: Recent activity, password enforce, and user profile

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #326 and #332 
**Force change password (including user profile change modal)**
[Force change password.webm](https://github.com/kartoza/miniSASS/assets/7352963/08bb8a87-35cc-4c0e-98e3-e15c1ad4dd81)

**Recent activity**
[Recent activity.webm](https://github.com/kartoza/miniSASS/assets/7352963/fea5f4dd-766c-4c6f-aaa1-67a98eba18e3)

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 3 sec

**Review by NyakudyaA — COMMENTED** [review]
LGTM @zamuzakki , just a few questions how are we determining if a user is an existing user?

As a follow up PR can we move the Logout button to be under the drop down menu which you have implemented because the Logout is very big and blocking that menu option.

Also a nice to have feature would be the ability to add a user's photo on the profile and this will show up on that menu instead of that generic icon, we can add this as a ticket

**Comment by zamuzakki** [comment]
@NyakudyaA Old user will have this field set to False by default. https://github.com/kartoza/miniSASS/blob/3a1ca9321aa5010aa6399417dbb93fd971ae2aad/django_project/minisass_authentication/models.py#L32
When password is updated, that field is set to True: https://github.com/kartoza/miniSASS/blob/3a1ca9321aa5010aa6399417dbb93fd971ae2aad/django_project/minisass_authentication/views.py#L290

When a new user register, that field would be set to True
https://github.com/kartoza/miniSASS/blob/3a1ca9321aa5010aa6399417dbb93fd971ae2aad/django_project/minisass_authentication/views.py#L207

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 54 sec

**Review by NyakudyaA — APPROVED** [review]
LGTM

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 43 sec

**Pull request merged**
