### PR TITLE
Add coordinates form, switching between DD and DMS

### LINKED ISSUE #283: DMS or Lat/long data form figma design
We need the user to select if they want DMS or Lat/long type of form and upon selecting, we show the appropriate one. Please create the wireframe for that 
image

### PR DESCRIPTION
**Pull request by meomancer**
This will fix https://github.com/kartoza/miniSASS/issues/283

https://github.com/kartoza/miniSASS/assets/4530905/d35128ec-81c9-4b1a-9558-e2e1da7cc133

### CODE REVIEW

**Comment by NyakudyaA** [comment]
@meomancer Your gif is saying it's corrupt

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 24 sec

**Comment by meomancer** [comment]
Hi @NyakudyaA It is mp4
I can see it also on incognito, maybe can you refresh it?

**Comment by NyakudyaA** [comment]
> Hi @NyakudyaA It is mp4 I can see it also on incognito, maybe can you refresh it?

Maybe firefox is broken, works on chrome

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 18 sec

**Pull request merged**
