### PR TITLE
Improve homepage slideshow

### PR DESCRIPTION
**Pull request by tinashechiraya**
Description

slider now has a fade animation and the pictures change slowly 
I have also added some icons to return to previous or move to next picture

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 22 sec

**Review by NyakudyaA — COMMENTED** [review]
GIF 


https://github.com/kartoza/miniSASS/assets/70011086/3877ba62-3882-4cb1-8eb5-6c6273fc9985

**Review by NyakudyaA — CHANGES_REQUESTED** [review]
The fade-in shows a white background, Can we implement something like https://youtu.be/k9pOWBPZ3aQ

@NyakudyaA can we test this on staging . the white that appeared is because there was no image on the next transition but in the case that there are images it won't be like that . it will be the same as on the video you shared

**Review by NyakudyaA — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 28 sec

**Pull request merged**
