### PR TITLE
User profile guide

### PR DESCRIPTION
**Pull request by ketankartoza**
This PR is for the issue #995

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 57 sec

**Review by Jeremy-Prior — APPROVED** [review]
LGTM

**Comment by Jeremy-Prior** [comment]
@ketankartoza please address the merge conflicts.

**Review by Jeremy-Prior — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 1 sec

**Pull request merged**
