### PR TITLE
Login api

### PR DESCRIPTION
**Pull request by tinashechiraya**
Description:

now the user can login and logout of the site from the frontend.

The api for checking a users auth status

check authentication status

the api for login out the user 

logout_user_api

still todo:
-[ ] add the token to the axios headers of every request so that it can validate and confirm the user is authenticated ,this will also ensure on the frontend the logout button wil continue to appear as long as the user is logged in 
I will create a seperate pr for the tokens and refreshing them on the frontend

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 6 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 5 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 58 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 49 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 1 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 26 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 18 sec

**Review by dimasciput — APPROVED** [review]

**Comment by dimasciput** [comment]
@tinashechiraya please fix the conflicts

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 30 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 59 sec

**Pull request merged**
