### PR TITLE
Add data forms and UI updates

### PR DESCRIPTION
**Pull request by tinashechiraya**
https://github.com/kartoza/miniSASS/assets/70011086/b0528f78-c3cb-4f1a-b856-1b4262573c36

Description:

I have added additional fields to the data input form when the user clicks type in coordinates
I have added the score form which is rendered when the user clicks the next button

still TODO
fetch dynamic data from api i.e. groups, sensitivity score, and images

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 52 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 56 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 14 sec

**Comment by NyakudyaA** [comment]
@tinashechiraya Can we link to issues that we are working on i.e https://github.com/kartoza/miniSASS/issues/118

**Comment by tinashechiraya** [comment]
this pr was for the ui only this has been merged in another pr #226

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 41 sec

**Pull request closed without merging**
