### PR TITLE
fix container error

### PR DESCRIPTION
**Pull request by NyakudyaA**
Starting locally I get the error

````
minisass-django-1  | Deleting 'js/GeoExt/lib/GeoExt/data/ProtocolProxy.js'
minisass-django-1  | Found another file with the destination path 'images/icon_facebook.png'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every 
minisass-django-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
minisass-django-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
minisass-django-1  |     res = handle_func(*args, **kwargs)
minisass-django-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
minisass-django-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
minisass-django-1  |   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
minisass-django-1  |     res = instance.__dict__[self.name] = self.func(instance)
minisass-django-1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
minisass-django-1  |                        ^^^^^^^^^^^^^^^^^^^
minisass-django-1  |   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
minisass-django-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
minisass-django-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
minisass-django-1  |     return _bootstrap._gcd_import(name[level:], package, level)
minisass-django-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
minisass-django-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
minisass-django-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
minisass-django-1  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
minisass-django-1  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
minisass-django-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
minisass-django-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
minisass-django-1  |   File "/home/web/django_project/minisass/urls.py", line 35, in <module>
minisass-django-1  |     path('monitor/', include('monitor.urls')),
minisass-django-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 8 min 12 sec

**Comment by tinashechiraya** [comment]
@NyakudyaA Let's hold off on this one , I have just merged another one with @zamuzakki that had the fixes and updates

**Comment by NyakudyaA** [comment]
> @NyakudyaA Let's hold off on this one , I have just merged another one with @zamuzakki that had the fixes and updates

Cool, let me pull and compile again

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 47 sec

**Pull request closed without merging**
