### PR TITLE
Enable select site on map

### PR DESCRIPTION
**Pull request by tinashechiraya**
https://github.com/kartoza/miniSASS/assets/70011086/dc3cf93a-19a9-4a6e-b1c1-b7b18d580b50

Description
I have enabled the select site on map feat 
selecting a site will populate the fields 
I have also placed the buttons next to each other and the user is now able to upload site images on an existing site

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 12 sec

**Review by NyakudyaA — COMMENTED** [review]
The double clicking of the select on the map button to enable clicking and then click again to disable me worries me.

Could we either have an info button to explain how it works or
Automatically disable the action after a site has been selected or the info has been retrieved. I am just conscious that this button is now having a double action unlike other buttons 

@NyakudyaA an info icon will do but atm lets keep testing if these intergrations are not affecting existing features and are working as expected

**Comment by NyakudyaA** [comment]
@tinashechiraya can you add the info button and we can merge, we don't also want to keep adding more TODO. 


@NyakudyaA sorted 

https://github.com/kartoza/miniSASS/assets/70011086/2d445a38-de0a-427e-85a1-9cb4183f6e8d

maybe we can improve upon the instructions

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 40 sec

**Review by NyakudyaA — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 43 sec

**Pull request merged**
