### PR TITLE
Set values to NA

### PR DESCRIPTION
**Pull request by NyakudyaA**
Set value to NA instead of null

### CODE REVIEW

**Comment by tinashechiraya** [comment]
@NyakudyaA let's test this on https://minisass.dev.do.kartoza.com/ ... since changing it to 'NA' to be saved in the db will likely break the conditions on the frontend because on the frontend it checks if null then shows 'N/A'

**Comment by NyakudyaA** [comment]
> @NyakudyaA let's test this on https://minisass.dev.do.kartoza.com/ ... since changing it to 'NA' to be saved in the db will likely break the conditions on the frontend because on the frontend it checks if null then shows 'N/A'

Yes, we only need it to show NA not save the values, so maybe the logic is wrong there. Thought that value was not being saved

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 11 min

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 11 min

**Comment by tinashechiraya** [comment]
this is no longer needed or already implemented

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 49 sec

**Pull request closed without merging**
