### PR TITLE
Feature/121-302: Download Observation and Charts

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #121 and #302 
When working on @NyakudyaA's feedback on https://github.com/kartoza/miniSASS/pull/367, my work intersects with #121 so I worked on it and combine them in 1 PR.
I'm also closing https://github.com/kartoza/miniSASS/pull/367, as it is combined in this PR.

Screenrecord:
[Kazam_screencast_00071.webm](https://github.com/kartoza/miniSASS/assets/7352963/cd808629-c894-4178-8414-2de3ab88100e)

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 4 min 10 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 10 sec

**Comment by tinashechiraya** [comment]
@zamuzakki you have some merge conflicts

**Review by NyakudyaA — APPROVED** [review]
LGTM, I will merge this and you can do a followup to handle the image uploads

**Comment by zamuzakki** [comment]
@tinashechiraya I've addressed the merge conflict.
@NyakudyaA Thanks, I'll add image download in different PR.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 1 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 50 sec

**Pull request merged**
