### PR TITLE
Improve recent observations and add observations form

### PR DESCRIPTION
**Pull request by tinashechiraya**
https://github.com/kartoza/miniSASS/assets/70011086/ad9d058b-3cc1-4445-afd9-3749e42b912a

Description:
I have evenly spread the observtions to fill the the entire space
I have added a left arrow icon to help the user to go back and forth 
I have a view observation link to each observation that will navigate to the map and open the sidebar panel with more details
about the observation

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 28 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 7 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 22 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 37 sec

**Review by NyakudyaA — CHANGES_REQUESTED** [review]
Screenshot from 2023-11-18 15-27-23

- [x] Can we move the panel to the other side below the search? Also, make it fit below the blue navbar as an overlay to the map. If we keep it where we have it you obstruct the map layer controls etc and 
- [x] Align the text properly

for inspiration look at the side panel done by @dimasciput in [FBIS](https://freshwaterbiodiversity.org/map/#search/Arthropoda/taxon=&search=Arthropoda&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=32504&ecosystemType=River,Wetland,Open%20waterbody,Unspecified)

**Comment by tinashechiraya** [comment]
@NyakudyaA the tabs are just a placeholder to show the logic but as per figma design those will be dates ...as for the rest I will make the adjustments

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 11 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 5 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 41 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 41 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 45 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 32 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 28 sec

**Comment by NyakudyaA** [comment]
Can you please add the TODO section to a separate ticket? Also, strip out other issues not addressed here into a separate ticket.

**Comment by tinashechiraya** [comment]
https://github.com/kartoza/miniSASS/assets/70011086/f28d73e6-1e94-4c3d-88e9-917d3dad3e01

**Review by NyakudyaA — APPROVED** [review]
Looks good based on the PR gif, Maybe @dimasciput needs to review the code

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 37 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 53 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 58 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 43 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 43 sec

**Pull request merged**
