### PR TITLE
patch: set selected site value

### PR DESCRIPTION
**Pull request by tinashechiraya**
Description

with this when select site on map is selected and the user clicks an existing site all the field values for site details will be populated including the sites field which was currently remaining empty

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 6 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 13 sec

**Review by NyakudyaA — COMMENTED** [review]
GIF


https://github.com/kartoza/miniSASS/assets/70011086/4c10db01-6cf2-44b6-ade7-ff91dc5fd875

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 6 min 12 sec

**Review by NyakudyaA — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 36 sec

**Pull request merged**
