### PR TITLE
feat: add frontend urls to backend #207

### PR DESCRIPTION
**Pull request by tinashechiraya**
Description:

now when you refresh on frontend page it wont give a page not found error ,on how to ,map and password reset pages.

This is no longer neccessary

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 40 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 18 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 43 sec

**Comment by tinashechiraya** [comment]
@dimasciput ignore this pr im still testing if its working on the dev staging

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 50 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 32 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 41 sec

**Pull request closed without merging**
