### PR TITLE
Fix missing import and styles

### PR DESCRIPTION
**Pull request by tinashechiraya**
opening the registration modal was crashing because of a missing import
the cancel button was not showing because of missing styling
the sidebar panel was slightly far from the search bar

these things have been corrected

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 38 sec

**Comment by NyakudyaA** [comment]
Can you add a gif please or screenshot. Does this fix https://github.com/kartoza/miniSASS/issues/232


https://github.com/kartoza/miniSASS/assets/70011086/91ef22c9-3515-438f-abaf-4c8f01eb22ea

@NyakudyaA yes that should resolve that too

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 55 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 54 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 48 sec

**Comment by NyakudyaA** [comment]
Some text alignment issues
Screenshot from 2023-11-20 19-42-33

@NyakudyaA as per figma it was on the center but I have aligned it with the other items

align_avg_score

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 36 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 59 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 34 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 56 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 8 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 14 sec

**Comment by tinashechiraya** [comment]
https://github.com/kartoza/miniSASS/assets/70011086/b253c6f2-d62c-420a-a0c8-74db30078019

@NyakudyaA

**Review by dimasciput — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 21 sec

**Pull request merged**
