### PR TITLE
feature/432: Fix landing page

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #432 (except for responsiveness issue, recent observations, and newsletter Wordpress)
Screenrecord:
https://youtu.be/oEvBo1yVfjo

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 34 sec

**Review by NyakudyaA — CHANGES_REQUESTED** [review]
Can you also patch the submit results link, it now correctly goes to the form but it doesn't switch to the satellite base map like what the Add record does

**Comment by zamuzakki** [comment]
@NyakudyaA Will do. I'll also fix the conflict.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 19 sec

**Comment by zamuzakki** [comment]
@NyakudyaA I have patched the submit results. It now uses satellite basemap.
[Kazam_screencast_00084.webm](https://github.com/kartoza/miniSASS/assets/7352963/d5e6859a-bafd-4830-82f1-7df424f81740)

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 34 sec

**Review by NyakudyaA — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 31 sec

**Pull request merged**
