### PR TITLE
Updated Style to have larger symbols

### PR DESCRIPTION
**Pull request by Jeremy-Prior**
- Increased symbol size at max zoom (from size 3 to size 4)
image

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 10 sec

**Review by NyakudyaA — CHANGES_REQUESTED** [review]
@Jeremy-Prior We do not need to make a V2, I see you changed sizes in v2 , can we rather update v1 with the new sizes, git history can help us revert to a version, as long as the commit message is clear.

Side note, they also mentioned some of the icons to be a bit blurry, Anything we can do on that aspect ?

**Comment by Jeremy-Prior** [comment]
@NyakudyaA I'll update the v1 style

In theory the 2x sprites should solve the blurriness but they aren't pulling through correctly. I will investigate again

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 4 sec

**Comment by Jeremy-Prior** [comment]
@NyakudyaA 

- I have updated the V1 style.
- I have done some testing and don't appear to be able to make the symbols any less blurry for the moment. If I make a break through with more "HD" symbols I will open a new PR.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 24 sec

**Review by NyakudyaA — APPROVED** [review]

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 3 sec

**Pull request merged**
