### PR TITLE
Feature/373 image uploads UI improvements

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #373 
- [x] After selecting images, user is still able to add more images.
- [x] Add clear button to clear all selected images. When clicked, upload image modal is closed.
- [x] Align delete image button.

Demo:
[Kazam_screencast_00083.webm](https://github.com/kartoza/miniSASS/assets/7352963/7dd7847f-e339-4e50-9917-c1ce1bed762d)

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 4 min 34 sec

**Review by NyakudyaA — APPROVED** [review]
LGTM

**Comment by NyakudyaA** [comment]
Can you take a look at why the build checks are failing @zamuzakki and merge when it's green

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 4 min 3 sec

**Comment by zamuzakki** [comment]
@NyakudyaA It's failing when building docker images. I tried to check the details (https://jenkins.do.kartoza.com/job/kartoza/job/apps/job/minisass_build/822/console), but the page always loading. I'll rebuild on local and try to see what happened.

**Comment by zamuzakki** [comment]
@NyakudyaA The build passed, I'm merging the PR.

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 41 sec

**Pull request merged**
