### PR TITLE
Fix/588: Homepage navbar could not be clicked

### PR DESCRIPTION
**Pull request by zamuzakki**
This is PR for #588 
Homepage navbar cannot be clicked because it is covered by slideshow.
[Kazam_screencast_00099.webm](https://github.com/kartoza/miniSASS/assets/7352963/66a92ccf-94e9-4485-b6b6-6091a1062438)

### CODE REVIEW

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 5 min 47 sec

**Review by tinashechiraya — APPROVED** [review]
LGTM

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 4 min 54 sec

**Comment by lgkgh** [comment]
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 49 sec

**Pull request merged**
